apiVersion: v1
data:
  default.conf: |+
    server {
        listen       80;
        server_name  localhost;

        location / {
            proxy_pass {{ .Values.configmap.nginx.proxy }};
            proxy_hide_header      Strict-Transport-Security;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }

kind: ConfigMap
metadata:
  name: {{ include "swarm.fullname" . }}-nginx
  labels:
    {{- include "swarm.labels" . | nindent 4 }}
---
apiVersion: v1
data:
  service-name: {{ .Values.configmap.podlister.name | default "" }}
kind: ConfigMap
metadata:
  name: {{ include "swarm.fullname" . }}-podlister
  labels:
    {{- include "swarm.labels" . | nindent 4 }}

